version: '3.8'
# 컨테이너를 정의할 때 "app", "server", "database" 처럼 이름을 정의해주면 해당 이름으로 컨테이너명이 설정된다
services:
  database:
    container_name: mysql_service
    image: mysql:8.0.31-debian
    restart: always
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - 3306:${DB_PORT}
    volumes:
      - /data/:/var/lib/mysql # 리눅스 서버 일때 권한 오류시 사용 '"--user 1000'
      #- C:\data\:/var/lib/postgresql/data 윈도우 일 때
    networks:
      default_bridge:
        ipv4_address: 172.26.0.2

  server:
    container_name: Nginx_service
    restart: always
    build:
      context: ./dockerfiles
      dockerfile: dockerfile_nginx
    ports:
      - 80:80
    depends_on:
    - app
    networks:
      default_bridge:
        ipv4_address: 172.26.0.4

  app:
    container_name: FastAPI_service
    restart: always
    build: .
    entrypoint: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--access-logfile", "./gunicorn-access.log"]
    command: ["main:app", "--bind", "0.0.0.0:8000", "--workers", "4"]
    depends_on:
      - database
    networks:
      default_bridge:
        ipv4_address: 172.26.0.3

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16