FROM python:3.10.5
LABEL email="tyche0529@naver.com"
LABEL name="Moon Chae Woo"
LABEL version="1.0"
LABEL description="FASTAPI Application"

WORKDIR /app/

COPY [".", "."]

RUN pip install -r requirements.txt

#EXPOSE 8000

ENTRYPOINT [ "uvicorn", "main:app", "--reload"]
CMD ["--host", "0.0.0.0", "--port", "8000", "--workers=4"]